[package]
name = "tuat-typst"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["OJII3", "toufu24"]
license = "MIT"
description = "Typst Title Page Template for TUAT Students who major in Computer Science"
